-- 初始化扩展
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. 创建 users 表（与 Ent 模型一致）
CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL DEFAULT '',
    password TEXT NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. 创建 roles 表（与 Ent 模型一致）
CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    role_name VARCHAR(64) NOT NULL UNIQUE
);

-- 3. 创建 providers 表
CREATE TABLE IF NOT EXISTS providers (
    id TEXT PRIMARY KEY,
    api_url TEXT NOT NULL,
    model_type TEXT NOT NULL,
    name TEXT NOT NULL
);

-- 4. 创建 provider_tokens 表
CREATE TABLE IF NOT EXISTS provider_tokens (
    id TEXT PRIMARY KEY,
    token TEXT NOT NULL,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_provider_tokens_provider_id ON provider_tokens(provider_id);

-- 5. 创建 models 表
CREATE TABLE IF NOT EXISTS models (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    provider_model_name TEXT NOT NULL,
    provider_id TEXT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('active','disabled')),
    input_price DOUBLE PRECISION NOT NULL CHECK (input_price >= 0),
    output_price DOUBLE PRECISION NOT NULL CHECK (output_price >= 0),
    currency TEXT NOT NULL CHECK (currency IN ('USD','CNY'))
);
CREATE INDEX IF NOT EXISTS idx_models_provider_id ON models(provider_id);

-- 6. 创建 user_tokens 表
CREATE TABLE IF NOT EXISTS user_tokens (
    id TEXT PRIMARY KEY,
    token TEXT NOT NULL
);

-- 7. 创建 Casbin 策略表（标准结构，兼容 ent-adapter）
CREATE TABLE IF NOT EXISTS casbin_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ptype VARCHAR(100) NOT NULL DEFAULT '',
    v0 VARCHAR(100) NOT NULL DEFAULT '',
    v1 VARCHAR(100) NOT NULL DEFAULT '',
    v2 VARCHAR(100) NOT NULL DEFAULT '',
    v3 VARCHAR(100) NOT NULL DEFAULT '',
    v4 VARCHAR(100) NOT NULL DEFAULT '',
    v5 VARCHAR(100) NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_casbin_rules ON casbin_rules (ptype, v0, v1, v2);

-- 8. 初始化基础数据
-- 8.1 角色
INSERT INTO roles (role_name) VALUES 
    ('admin'),
    ('manager'),
    ('user')
ON CONFLICT (role_name) DO NOTHING;

-- 8.2 默认权限策略（仅 p 策略，不做 g 绑定）
-- API 权限
INSERT INTO casbin_rules (ptype, v0, v1, v2) VALUES
    ('p', 'admin', '/api/*', '*'),
    ('p', 'manager', '/api/users', 'GET'),
    ('p', 'manager', '/api/users', 'POST'),
    ('p', 'manager', '/api/tokens', '*'),
    ('p', 'user', '/api/profile/*', '*');

-- UI 权限
INSERT INTO casbin_rules (ptype, v0, v1, v2) VALUES
    ('p', 'admin', 'menu:*', 'view'),
    ('p', 'admin', 'page:*', 'view'),
    ('p', 'admin', 'button:*', 'view'),
    ('p', 'manager', 'menu:user_management', 'view'),
    ('p', 'manager', 'menu:token_management', 'view'),
    ('p', 'manager', 'page:user_list', 'view'),
    ('p', 'manager', 'page:token_list', 'view'),
    ('p', 'user', 'menu:dashboard', 'view'),
    ('p', 'user', 'page:profile', 'view');
