# Backend config for Docker runtime (file-based, no env)

# API server (management API)
api_server_host: "0.0.0.0"
api_server_port: 8080

# Internal engine server exposed by Go backend
engine_server_host: "0.0.0.0"
engine_server_port: 8081

# PostgreSQL
db_host: "postgres"
db_port: 5432
db_user: "axongate"
db_password: "axongate_password"
db_name: "axongate"
db_max_connections: 25
db_max_idle_conns: 5

# Logging
log_level: "info"
log_dir: "/var/log/ai-gateway"
api_log_file: "api.log"
engine_log_file: "engine.log"
log_max_size: 100
log_max_backups: 7
log_max_age: 30
